---
title: "Understanding the two types of uncertainty will help you live more confidently in a stochastic world"
subtitle: "Not all uncertainties are created equal."
author: "Mark Zobeck"
date: 2022-03-24
categories: ["Confident Uncertainty"]
tags: ["Stochasticism"]
slug: "two_types_of_uncertainty"
---

```{r, message = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE) 
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(error = FALSE)

library(tidyverse)
library(ggthemes)
library(gt)
library(plotly)
library(kableExtra)
# Settings
theme_set(theme_clean() +  
  theme(plot.background=element_blank()))

```

We live in a complex and often chaotic world. To live confidently, we have to know how to navigate uncertain paths.

We make decisions every single day. What do you eat in the morning? What route should you take to work? Do you invest in a certain stock? Do you hire a new employee? Etc...

How do we make good decisions when the outcomes are uncertain? We have to first understand the two types of uncertainty that are present in any decision because each type requires its own response.

## Aleatory uncertainty 

Aleatory uncertainty is uncertainty due to the inherent randomness in a process. Think of a single flip of a fair coin. There is a 50% chance it comes up heads and a 50% chance it comes up tales. Or think of the thoroughly shaken-up role of a fair die. There is a one in six chance of getting a 1 on every role. These probabilities are inherent in the system generating the outcome (coin flips and dice rolls) and there is no way to reduce the uncertainty about it.

## Epistemic uncertainty

Epistemic uncertainty is your uncertainty about the outcome of a decision. This uncertainty is reducible by gaining knowledge. It is uncertainty that exists in the mind of the observer and could be reduced through empirical evidence or logical argument. What is the atomic number of zenon? How long is your left 3rd toe? Who was the first cartoonist to draw Donal Duck? These are all things one is likely uncertain about right now but could Google or measure if needed.

## Bringing the two types together 

Suppose you have a bag of 20 marbles, and I ask you to predict the color of the next marble you pull out. You know some are blue and some red, but you don't know the relative proportions of each in the bag. There is both aleatory and epistemic uncertainty present in this scenario. If you were to start drawing marbles and put them to the side, you could count the relative proportions of what you draw out as you go and your epistemic uncertainty about that slowly reduce with each draw. Suppose you see 80% of the marbles are red and then dump them back in the bag. Now you know there is an 80% chance you will pull out a red marble on the next draw, which is the aleatory uncertainty inherent in the system. You've reduced your epistemic uncertainty as far as it can go, and now the rest is left up to aleatory chance.

## Living in light of uncertainty 

Differentiating the two types of uncertainty is important because each has its own approach. When faced with high epistemic uncertainty, the answer is to get more information. Reduce the epistemic uncertainty in decisions as far as you are able within your means and time constraints. If you hit mostly aleatory uncertainty, then there is nothing you can do to reduce it further unless you break the whole system, which is rarely an option but something to consider. If you can't intervene in the system, then you have to decide what benefits do you get from each potential outcome. If the benefits of a lower probability outcome far outway the benefits of a higher probability outcome, then it might make sense to go for the former. You've reached the point where you have to know what you want and decide if the probability of the outcome described by the aleatory uncertainty gives you enough payoff so that you should go for it.

Understanding these two types of uncertainty will help you take steady steps along uneven ground and navigate successfully to your utility-maximized future.

...Of course, nothing is ever that neat and tidy. Especially in this uncertain world. This is a good start but someday we'll have to talk about monsters that emerge from the dark abyss of radical uncertainty.
