project:
  type: website

website:
  title: "The Doctor's Dialectic"
  description: "The personal blog of Dr. Mark Zobeck"
  image: img/tdd_logo-a.png
  search: true
  reader-mode: true
  page-navigation: true
  site-url: https://www.thedoctorsdialectic.com
  google-analytics: "G-D9Y95ZTCEN"
  open-graph: true
  twitter-card: true
  favicon: img/tdd_logo-a.png
    
  navbar:
    background: white
    logo: img/d_logo.jpg
    #logo-alt: "The Doctor's Dialectic logo."
    title: "The Doctor's Dialectic"
    collapse-below: lg
    pinned: false
    left:
      - href: index.qmd
        text: "Home"
      - href: docs/about/index.qmd
        text: "About"
      - href: docs/research/index.qmd
        text: "Research"
      - href: blog.qmd
        text: "Blog"
        
    right:
      - icon: twitter
        href: https://twitter.com/MarkZobeck
      - icon: github
        href: https://github.com/mzobeck/tdd_site
      - icon: envelope
        aria-label: email
        href: "mailto:mzobeck@gmail.com"  
 
exclude:
  - staging/* 
 
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: custom.css
    toc: true
