project:
  type: website

website:
  title: "The Doctor's Dialectic"
  description: "The personal blog of Dr. Mark Zobeck"
  image: img/tdd_logo-a.png
  search: true
  reader-mode: true
  page-navigation: true
  site-url: https://www.thedoctorsdialectic.com
  google-analytics: "G-D9Y95ZTCEN"
  open-graph: true
  twitter-card: true
  favicon: img/tdd_logo-a.png
    
  navbar:
    background: white
    logo: img/d_logo.jpg
    #logo-alt: "The Doctor's Dialectic logo."
    title: "The Doctor's Dialectic"
    collapse-below: lg
    pinned: false
    left:
      - href: index.qmd
        text: "Home"
      - href: docs/about/index.qmd
        text: "About"
      - href: docs/research/index.qmd
        text: "Research"
      - href: blog.qmd
        text: "Blog"
#      - href: docs/epistemic_limits/index.qmd
#        text: "Epistemic Limits"
        
    right:
      - icon: twitter
        href: https://twitter.com/MarkZobeck
      - icon: github
        href: https://github.com/mzobeck/tdd_site
      - icon: envelope
        aria-label: email
        href: "mailto:mzobeck@gmail.com"  
        
#  sidebar:
#    - id: epistemic-limits
#      title: "Epistemic Limits"
#      sytle: "floating"
#      colapse-level: 1
#      align: left
#      contents:
#        - href: docs/epistemic_limits/index.qmd
#          text: "Epistemic Limits"
#        - section: "The Menagerie of Unknowables"
#          href: docs/epistemic_limits/menagerie/index.qmd
#          contents:
#            - text: "Absolute Epistemic Limits"
#              href: docs/epistemic_limits/menagerie/absolute_limits/index.qmd
#              contents: 
#                - section: "First-order"
#                  contents:
#                    - section: "Logical"
#                    - section: "Mathematical"
#                    - section: "Computation"
#                      contents:
#                        - text: "The Halting Problem"
#                          href: docs/epistemic_limits/menagerie/absolute_limits/halting_problem/index.qmd
#                    - section: "Scientific"

exclude:
  - staging/* 
 
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: custom.css
    toc: true
    



