---
title: "Let the data flow: how to move information to the people who need it in a Global Health organization"
subtitle: "Information flow creates a healthy healthcare system."
author: "Mark Zobeck"
date: 2022-03-21
categories: ["Data Science + Global Health"]
tags: ["Data science"]
slug: "let-the-data-flow"
---

```{r, message = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE) 
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(error = FALSE)

library(tidyverse)
library(ggthemes)
library(gt)
library(plotly)
library(kableExtra)
# Settings
theme_set(theme_clean() +  
  theme(plot.background=element_blank()))

```

If a health facility is adequately staffed with doctors, nurses, and other providers, and it is well supplied with medicines and medical equipment, then it has everything it needs to deliver care effectively, right?

Unfortunately, this is wrong. If effective healthcare delivery only required sufficient numbers of providers who possess sufficient equipment, then the prescription to include care in resource-constrained settings would be clear: more people and more stuff!

Examples abound where care is delivered ineffectively despite sufficient people with the right stuff. Patients may not be referred to the correct treatment facility. Doctors may not be able to diagnose patients effectively despite the presence of adequate laboratory and radiographic equipment. Hospital floor staff may not know which patients are sickest and need acute treatment despite vital signs being regularly obtained by nurses. While people are stuff are necessary for effective healthcare delivery, they are not sufficient. There is a missing ingredient that ties all of these examples of dysfunction together.

## **Information flow is key to effective healthcare delivery**

Information flow means that the right information comes to the right person at the right time so that effective healthcare decisions can be made.

Information flow during the referral process means that the clinical information about flows from the patient to the doctor, who in turn delivers the needed referral information to the patient and to the referring center, which can also reach out with visit information to the patient to assure timely arrival.

To obtain diagnostic information, doctors need to send patients to the lab where information can flow from the patient to a machine that transforms the results into diagnostic information that is passed back to the doctor.

To intervene on an acutely decompensating patient, information about the patient's health state needs to flow to the nurses who transmit the information to physicians in a timely manner for acute intervention.

## **Information flow is like the nervous system of the health organization**

Information flow transmits both sensory and motor information throughout the functional units of the healthcare organism. A body can have the healthiest heart possible, but if its actions and outputs cease to be coordinated with the activity of the rest of the organs, then the organism soon falls into a very poor state of health. So too, a health system with well-trained doctors but uncoordinated actions with other providers or with laboratory equipment quickly becomes dysfunctional.

## **Information flow reframes healthcare as a dynamic, complex system**

Information flows show that healthcare is a dynamic system as the state of each part is constantly changing and reacting to other parts in the system. It also shows that healthcare is a complex system with many interlocking parts causing unexpected outcomes.

Information flow shows the connections between the parts of the system. You still may not be able to predict the long-term outcomes of a complex system, but if you can see the information flow, you can see how the system grows and changes over time so that you can slowly shape its evolutionary trajectory.

## **People and stuff are insufficient to deliver effective care if information is not flowing freely in the system.**

The goal for health systems to deliver effective care over time for all patients cannot be achieved if information does not flow in the system to coordinate and inform its activities.

This is why data science is a vital capability for health systems in low-resource settings. Data science can move information and provide insights as fast as the date are able to be gathered and collected. With commitment and steady effort, it is possible to build the informational nervous system that the healthcare organism needs to survive and thrive.
